repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: tofu-fmt
      - id: tofu-validate
      - id: tflint
      - id: terragrunt-hcl-fmt
  - repo: local
    hooks:
      - id: trivy-secrets
        name: Trivy secret scan
        language: system
        entry: trivy fs .
        pass_filenames: false
        always_run: true