# TFlint triggers an unused variable error cause the `provider_kubernetes.tf` file is
# generated by terragrunt at runtime.
# We can safely ignore it
# tflint-ignore: terraform_unused_declarations
variable "cluster_name" {
  description = "The name of the cluster"
  type        = string
}

# https://artifacthub.io/packages/helm/argo/argo-cd
variable "helm_chart_version" {
  description = "The version of the helm chart of installing argocd"
  type        = string
}

variable "helm_values" {
  description = "Helm values to pass to the ArgoCD chart"
  type        = any
  default     = {}
}