# TFlint triggers an unused variable error cause the `provider_helm.tf` and
# `provider_k8s_base.tf` files are generated by terragrunt at runtime.
# We can safely ignore it
# tflint-ignore: terraform_unused_declarations
variable "cluster_name" {
  description = "The name of the EKS cluster"
  type        = string
}

variable "name" {
  description = "Name of the Helm release"
  type        = string
}

variable "repository" {
  description = "URL of the Helm chart repository. Omit for a local chart (chart set to a directory path)."
  type        = string
  default     = null
}

variable "chart" {
  description = "Name of the Helm chart"
  type        = string
}

variable "namespace" {
  description = "Kubernetes namespace to install the chart into"
  type        = string
}

variable "create_namespace" {
  description = "Create the namespace if it does not already exist"
  type        = bool
  default     = true
}

variable "helm_chart_version" {
  description = "Version of the Helm chart to install. Omit for a local chart, its own Chart.yaml already pins one."
  type        = string
  default     = null
}

variable "helm_values" {
  description = "Values to pass to the Helm chart"
  type        = any
  default     = {}
}

variable "helm_set" {
  description = "Individual Helm values to set, passed as-is to the helm_release set attribute"
  type = list(object({
    name  = string
    value = string
    type  = optional(string)
  }))
  default = []
}

variable "helm_set_sensitive" {
  description = "Individual Helm values to set as sensitive, passed as-is to the helm_release set_sensitive attribute"
  type = list(object({
    name  = string
    value = string
  }))
  default = []
}

variable "timeout" {
  description = "Time in seconds to wait for any individual Kubernetes operation during install/upgrade/uninstall"
  type        = number
  default     = 300
}
